### ISSUE TITLE
页面向下滚动后，总是会自动滚动到第一个锚点

### ISSUE THREAD

**Issue by AkiyamaMinami** [latteandcat/Blog#1]
hi，代码本地运行后，note页面的文章向下滚动后，页面会自己滚动到第一个锚点，无法滚动到别的锚点。
想请问下这个问题您这里遇到过嘛？该怎么解决呢？
![chrome-capture-2022-7-5 (1) (1)](https://user-images.githubusercontent.com/31888190/182996817-6098dc41-6221-4051-831b-1af086fc7d40.gif)

**Comment by latteandcat** [comment]
不清楚原因，我的显示正常，你在[blog](https://blog.smallsunnyfox.com/)试一下看看

**Comment by latteandcat** [comment]
我现在用的版本很久没升了我的建议是用主题重新构建，或者我把package-lock.json发你试试

**Comment by AkiyamaMinami** [comment]
> 我现在用的版本很久没升了我的建议是用主题重新构建，或者我把package-lock.json发你试试

感谢回复~ 我找到解决方案了，应该是我用的版本1.6.14的Bug。
![image](https://user-images.githubusercontent.com/31888190/183629747-38de704d-8e39-452d-92c3-41d049a99ebd.png)
至于本地运行您的博客也出现这种情况，我发现lock文件版本也是1.6.14。
![image](https://user-images.githubusercontent.com/31888190/183630451-e85c1bd1-ee8a-4429-9489-2503875b3650.png)
