### ISSUE TITLE
麻烦教教我

### ISSUE THREAD

**Issue by shkmzzh** [latteandcat/Blog#8]
你好，为什么呢我和博主你设置一样的，notes界面，但是我点击右边小侧边栏时会莫名往上跳，左侧的侧边栏有时还打不开呢

**Comment by latteandcat** [comment]
> 你好，为什么呢我和博主你设置一样的，notes界面，但是我点击右边小侧边栏时会莫名往上跳，左侧的侧边栏有时还打不开呢

先检查一下依赖版本是否一致，然后右侧莫名上跳不太清楚，左侧确保侧边栏配置项里的页面存在应该就没问题
